#!/bin/bash
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/term_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/term_defect_genes/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/term_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/term_defect_genes/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/term_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/term_defect_genes/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/term_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/term_defect_genes/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/term_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/term_defect_genes/hist_TTS_input.tsv

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/no_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/non_term_defect_genes/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/no_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/non_term_defect_genes/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/no_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/non_term_defect_genes/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/no_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/non_term_defect_genes/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_02_bed_files/no_defect_genes_TTS_isolated_expressed_genes.bed hg38 -size -20000,20000 -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/all_iso_exp_genes/non_term_defect_genes/hist_TTS_input.tsv