#!/bin/bash
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_dec/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_dec/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_dec/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_dec/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_dec/hist_TTS_input.tsv
echo "finished with Ser2P 20kb dec genes"

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_inc/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_inc/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_inc/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_inc/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_inc/hist_TTS_input.tsv
echo "finished with Ser2P 20kb inc genes"

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_nc/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_nc/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_nc/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_nc/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_20kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_20kb_nc/hist_TTS_input.tsv
echo "finished with Ser2P 20kb no change genes"

echo "half-way there :)"

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_dec/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_dec/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_dec/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_dec/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_dec_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_dec/hist_TTS_input.tsv
echo "finished with Ser2P 5kb dec genes"

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_inc/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_inc/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_inc/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_inc/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_inc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_inc/hist_TTS_input.tsv
echo "finished with Ser2P 5kb inc genes"

annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_nc/hist_TTS_NHS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Rpb1_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_nc/hist_TTS_HS_Rpb1_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/NHS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_nc/hist_TTS_NHS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/HS_Ser2P_pooled_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_nc/hist_TTS_HS_Ser2P_pooled.tsv
annotatePeaks.pl /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/07_03_investigating_biological_questions/07_03_bed_files/Ser2p_nc_5kbds_genes_2kb_upstream_to_20kb_ds.bed hg38 -size "given" -hist 200 -norm 5E7 -d /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/03_tag_directories/input_TD > /Users/goodrichlab/Desktop/Katy_ChIPseq1/hg38/07_analysis/TTS_hist/Ser2P_categories/Ser2P_5kb_nc/hist_TTS_input.tsv
echo "finished with Ser2P 5kb no change genes"